"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SYNC_INTERVAL_MS = exports.DEFAULT_CANVAS_HEIGHT = exports.DEFAULT_CANVAS_WIDTH = exports.HOUSE_COUNT = exports.HOUSE_TILE_SPACING = exports.HOUSE_START_TILE_X = exports.TILE_SIZE = exports.BUILDING_GROUND_Y = void 0;
exports.BUILDING_GROUND_Y = 420;
exports.TILE_SIZE = 32;
exports.HOUSE_START_TILE_X = 7;
exports.HOUSE_TILE_SPACING = 4;
exports.HOUSE_COUNT = 30;
exports.DEFAULT_CANVAS_WIDTH = 960;
exports.DEFAULT_CANVAS_HEIGHT = 640;
exports.SYNC_INTERVAL_MS = 100;
