"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PartyManagementScreen = PartyManagementScreen;
const jsx_runtime_1 = require("preact/jsx-runtime");
const hooks_1 = require("preact/hooks");
const store_1 = require("../state/store");
const stats_1 = require("@/core/algorithms/stats");
const SimpleSprite_1 = require("../sprites/SimpleSprite");
const warnIfPlaceholderSprite_1 = require("../sprites/utils/warnIfPlaceholderSprite");
const mappings_1 = require("../sprites/mappings");
require("./PartyManagementScreen.css");
function PartyManagementScreen({ onClose }) {
    const { team, roster } = (0, store_1.useStore)((s) => ({
        team: s.team,
        roster: s.roster,
    }));
    const [selectedUnitId, setSelectedUnitId] = (0, hooks_1.useState)(null);
    if (!team) {
        return ((0, jsx_runtime_1.jsx)("div", { class: "party-management-overlay", onClick: onClose, children: (0, jsx_runtime_1.jsxs)("div", { class: "party-management-container", onClick: (e) => e.stopPropagation(), children: [(0, jsx_runtime_1.jsx)("div", { class: "party-error", children: "No team data available" }), (0, jsx_runtime_1.jsx)("button", { class: "close-btn", onClick: onClose, children: "Close" })] }) }));
    }
    const activeUnitIds = new Set(team.units.map((u) => u.id));
    const selectedUnit = roster.find((u) => u.id === selectedUnitId);
    const selectedStats = selectedUnit ? (0, stats_1.calculateEffectiveStats)(selectedUnit, team) : null;
    return ((0, jsx_runtime_1.jsx)("div", { class: "party-management-overlay", onClick: onClose, children: (0, jsx_runtime_1.jsxs)("div", { class: "party-management-container", onClick: (e) => e.stopPropagation(), children: [(0, jsx_runtime_1.jsxs)("div", { class: "party-management-header", children: [(0, jsx_runtime_1.jsx)("h1", { children: "Unit Compendium" }), (0, jsx_runtime_1.jsx)("button", { class: "close-btn", onClick: onClose, "aria-label": "Close compendium", children: "\u00D7" })] }), (0, jsx_runtime_1.jsx)("div", { class: "party-instructions", children: (0, jsx_runtime_1.jsx)("p", { children: "Browse your full roster and review each unit's stats. The battle formation and loadouts you see here are only a snapshot\u2014final selections happen on the Pre-Battle screen before each fight." }) }), (0, jsx_runtime_1.jsxs)("div", { class: "party-content", children: [(0, jsx_runtime_1.jsxs)("div", { class: "party-section", children: [(0, jsx_runtime_1.jsxs)("h2", { children: ["Roster (", roster.length, ")"] }), (0, jsx_runtime_1.jsx)("div", { class: "party-grid", children: roster.map((unit) => {
                                        const isActive = activeUnitIds.has(unit.id);
                                        const isSelected = selectedUnitId === unit.id;
                                        return ((0, jsx_runtime_1.jsxs)("div", { class: `party-member-card ${isSelected ? 'selected' : ''} ${isActive ? 'active' : ''}`, onClick: () => setSelectedUnitId(unit.id), children: [(0, jsx_runtime_1.jsx)("div", { class: "member-icon", children: (() => {
                                                        const portraitId = (0, mappings_1.getPortraitSprite)(unit.id);
                                                        (0, warnIfPlaceholderSprite_1.warnIfPlaceholderSprite)('PartyManagementScreen', portraitId);
                                                        return ((0, jsx_runtime_1.jsx)(SimpleSprite_1.SimpleSprite, { id: portraitId, width: 64, height: 64, style: { borderRadius: '8px' } }));
                                                    })() }), (0, jsx_runtime_1.jsxs)("div", { class: "member-info", children: [(0, jsx_runtime_1.jsx)("div", { class: "member-name", children: unit.name }), (0, jsx_runtime_1.jsxs)("div", { class: "member-stats", children: ["Lv: ", unit.level] }), (0, jsx_runtime_1.jsx)("div", { class: "member-element", children: unit.element }), (0, jsx_runtime_1.jsx)("div", { class: "member-role", children: unit.role }), isActive && (0, jsx_runtime_1.jsx)("div", { class: "active-badge", children: "Roster Slot" })] }), isSelected && ((0, jsx_runtime_1.jsx)("div", { class: "selection-indicator", children: "Selected" }))] }, unit.id));
                                    }) })] }), selectedUnit && selectedStats && ((0, jsx_runtime_1.jsxs)("div", { class: "party-section unit-details", children: [(0, jsx_runtime_1.jsx)("h2", { children: selectedUnit.name }), (0, jsx_runtime_1.jsxs)("div", { class: "detail-grid", children: [(0, jsx_runtime_1.jsxs)("div", { class: "detail-row", children: [(0, jsx_runtime_1.jsx)("span", { class: "detail-label", children: "Level:" }), (0, jsx_runtime_1.jsx)("span", { class: "detail-value", children: selectedUnit.level })] }), (0, jsx_runtime_1.jsxs)("div", { class: "detail-row", children: [(0, jsx_runtime_1.jsx)("span", { class: "detail-label", children: "Element:" }), (0, jsx_runtime_1.jsx)("span", { class: "detail-value", children: selectedUnit.element })] }), (0, jsx_runtime_1.jsxs)("div", { class: "detail-row", children: [(0, jsx_runtime_1.jsx)("span", { class: "detail-label", children: "Role:" }), (0, jsx_runtime_1.jsx)("span", { class: "detail-value", children: selectedUnit.role })] }), (0, jsx_runtime_1.jsx)("div", { class: "detail-divider" }), (0, jsx_runtime_1.jsxs)("div", { class: "detail-row", children: [(0, jsx_runtime_1.jsx)("span", { class: "detail-label", children: "HP:" }), (0, jsx_runtime_1.jsxs)("span", { class: "detail-value", children: [selectedUnit.currentHp, " / ", selectedStats.hp] })] }), (0, jsx_runtime_1.jsxs)("div", { class: "detail-row", children: [(0, jsx_runtime_1.jsx)("span", { class: "detail-label", children: "ATK:" }), (0, jsx_runtime_1.jsx)("span", { class: "detail-value", children: selectedStats.atk })] }), (0, jsx_runtime_1.jsxs)("div", { class: "detail-row", children: [(0, jsx_runtime_1.jsx)("span", { class: "detail-label", children: "DEF:" }), (0, jsx_runtime_1.jsx)("span", { class: "detail-value", children: selectedStats.def })] }), (0, jsx_runtime_1.jsxs)("div", { class: "detail-row", children: [(0, jsx_runtime_1.jsx)("span", { class: "detail-label", children: "MAG:" }), (0, jsx_runtime_1.jsx)("span", { class: "detail-value", children: selectedStats.mag })] }), (0, jsx_runtime_1.jsxs)("div", { class: "detail-row", children: [(0, jsx_runtime_1.jsx)("span", { class: "detail-label", children: "SPD:" }), (0, jsx_runtime_1.jsx)("span", { class: "detail-value", children: selectedStats.spd })] }), (0, jsx_runtime_1.jsx)("div", { class: "detail-divider" }), (0, jsx_runtime_1.jsxs)("div", { class: "detail-section", children: [(0, jsx_runtime_1.jsxs)("h3", { children: ["Abilities (", selectedUnit.abilities.length, ")"] }), (0, jsx_runtime_1.jsx)("div", { class: "ability-list", children: selectedUnit.abilities.map((ability) => ((0, jsx_runtime_1.jsxs)("div", { class: "ability-item", children: [(() => {
                                                                const iconId = (0, mappings_1.getAbilityIconSprite)(ability.id);
                                                                (0, warnIfPlaceholderSprite_1.warnIfPlaceholderSprite)('PartyManagementScreen', iconId);
                                                                return ((0, jsx_runtime_1.jsx)(SimpleSprite_1.SimpleSprite, { id: iconId, width: 24, height: 24, style: { marginRight: '8px', borderRadius: '4px' } }));
                                                            })(), (0, jsx_runtime_1.jsx)("span", { class: "ability-name", children: ability.name }), ability.manaCost > 0 && ((0, jsx_runtime_1.jsxs)("span", { class: "ability-cost", children: ["[", ability.manaCost, "]"] }))] }, ability.id))) })] })] })] }))] })] }) }));
}
